### ISSUE TITLE
While initializing, be more verbose about what's going on.

### ISSUE THREAD

**Issue by mk-pmb** [superpowers-extra/discover-superpowers-game#4]
I tried running the [demo game](https://sparklinlabs.itch.io/discover-superpowers), but all I got was a full page link to the game engine.
I guessed that I'd have to grant some permissions in NoScript and RequestPolicy, still it would have been nice to be reminded by the game loader, telling me that some JavaScripts failed to load.

What I wouldn't have guessed is that while I was looking at the game engine ad, the game was trying to initialize WebGL. It should have said so, then I'd have waited a bit longer and not considered it dead. Unfortunately, "dead on arrival without meaningful error message" is what 95% of HTML 5 games turn out for me, so debug hints would be a nice feature.

Thanks to a friend, I found out that if I just wait long enough, I can get to

> Error: Failed to initialize renderer. Your device might not support WebGL.

… so I'll retry on another machine soon&trade;, or try 2D game. I hope by then I'll get an error message telling me which host/port the failed websocket connection tried to contact, so I can whitelist that connection. ;-)

**Comment by mk-pmb** [comment]
So now I downloaded Superpowers (0.19.0-linux-ia32), cloned this game, loaded it into the IDE, clicked the play button, it initialized the game… let me pause for an in-between summary: Nice work, best "Indie" Game IDE I've seen so far!

… then the game loads and announces:

> Failed to initialize renderer. Your device might not support WebGL.
> ([Screenshot](http://temp.svenvanbolt.de/discover-fail.bc338d96.jpeg))

I wonder, how can this be? There's no border around the IDE windows, so I think it uses its own browser? But if it ships its own browser, why an incompatible one?

Or is it my graphics card? DirectX 3D games run fine in wine, however. Should I try the windows build of Superpowers and run it in wine as well?

**Comment by elisee** [comment]
Hi!

> I hope by then I'll get an error message telling me which host/port the failed websocket connection tried to contact, so I can whitelist that connection. ;-)

WebGL is graphics-related, not socket-related, so not sure what you mean.

> I wonder, how can this be? There's no border around the IDE windows, so I think it uses its own browser? But if it ships its own browser, why an incompatible one?

Superpowers runs on Electron, which is a Chrome-based HTML5 app runtime.

> Or is it my graphics card? DirectX 3D games run fine in wine, however. Should I try the windows build of Superpowers and run it in wine as well?

It is most probably a graphics driver issue. WebGL might not initialize if your GPU or driver is blacklisted / unsupported. Do you get a rotating cube when opening http://get.webgl.org/ in your browser?

**Comment by DarrenCook** [comment]
@elisee I think it would've made more sense to close this issue, and reply on the more general one, as this issue is not specific to this game? (I think this can still be done.)

Anyway, I'll reply here for the moment. In the following issue the problem turned out to be a difference between the Electron browser and Chrome browser, with a custom shader: https://github.com/superpowers-extra/fat-kevin-game/issues/1
discover-superpowers-game doesn't use a custom shader, so that exact problem won't be the issue here; the thing I wanted to point out was how you can use Chrome or Firefox to test (and in fact run the IDE).

BTW, all superpower games have been fine for me. I'm using Mint 17, i.e. Ubuntu 14, whereas you seem to be using Ubuntu 12. So it might be newer driver versions?  But I'm also using 64-bit Linux, and you appear to be using 32-bit? (Or you've downloaded the wrong version of superpowers.)
Perhaps you could try a live CD of a new distro, and/or a 64-bit distro, and see if that makes things work.

**Comment by mk-pmb** [comment]
On Ubuntu 12.04.5 LTS precise, the website test failed and told me it's probably due to old drivers.
On Ubuntu 14.04.4 LTS trusty, Firefox shows a spinning cube and "Your browser supports WebGL", so I'll move my Superpowers there and retry.
Is there any chance I can use Superpowers with 2D games on my old precise Ubuntu?

> WebGL is graphics-related, not socket-related, so not sure what you mean.

The relation is their frequent use in HTML5 games, so I was looking forward to reaching the next stage of usual HTML5 game problems, once I cleared the WebGL stage. I think I actually even had it a few minutes ago, but can't currently reproduce it due to other bugs.

**Comment by elisee** [comment]
> The relation is their frequent use in HTML5 games, so I was looking forward to reaching the next stage of usual HTML5 game problems, once I cleared the WebGL stage. I think I actually even had it a few minutes ago, but can't currently reproduce it due to other bugs.

Haha I see, ok.

> Is there any chance I can use Superpowers with 2D games on my old precise Ubuntu?

2D games in the "Superpowers Game" system use WebGL too, with an orthographic camera, so it doesn't really make a difference whether it's 2D or 3D.

> @elisee I think it would've made more sense to close this issue, and reply on the more general one, as this issue is not specific to this game? (I think this can still be done.)

I guess the issue could make sense in the `superpowers-game` repository, but `superpowers-app` was definitely not the place since the app doesn't deal with WebGL stuff at all. But anyway, I think here is fine now ^_^

@mk-pmb As far as I understand, it's a Linux graphics driver problem in general, not a Superpowers bug, and you've found a way to make it work by updating so I'll close the issue for now. Feel free to re-open if you need more help!
